### PR TITLE
Pull Request for GDSC task by Vaibhav with Corrected Code

### PR DESCRIPTION
**Pull request by IAlgorithmia**
Re: #32

I have added a new course in the "courses" folder, and also a question paper on Discrete Mathematics in the "question-paper" folder.

### CODE REVIEW

**Comment by GetPsyched** [comment]
You don't need to open a new PR. Pushing commits to that branch automatically adds those commits to your existing PR.

**Comment by IAlgorithmia** [comment]
Sir, can you please tell me if there are still some mistakes?

**Comment by GetPsyched** [comment]
Yes, I will in some time; busy rn.

**Comment by GetPsyched** [comment]
Hmm

**Pull request closed without merging**
